[package]
name = "d2sw_tiled_project"
version = "0.2.2"
edition = "2021"

[dependencies]
const_format = "0.2"
byteorder = "1.4"
png = "0.17"
toml = "0.5"
# toml_edit = { version = "0.14", features = ["serde", "easy", "perf"] }
serde = { version = "1.0", features = ["derive"] }
# grep-cli = "0.1"
# hot-lib-reloader = "0.6"
# hot-lib-reloader-macro = "0.6"
memchr = "2.5"
